= Actionable Advice
// batchspell: add RFI Reddit topbot PVA TPU TPE bioplastics makerspace

== Build-time advice

Some advice in the link:setup.html[SV08 setup guide] generalizes to
other printer types:

1. Loctite your frame screws against vibration.

2. Tack down your stepper-motor connectors with hot glue against
   vibration.

3. Apply armor tape anywhere wire bundles might rub against a metal
   edge.

4. Apply stick-on heatsinks to the processor chops on your mainboard

5. Put a snap-on ferrite choke on your toolhead cable against RFI.

== Managing filament

When you dismount a filament spool, don't let the filament end
flop around - that's a fast way to get filament tangles on your spool
that will trouble you later. Thread the end through at least one of the
holes near the spool rim; ideally, two of them.

Moist filament is a major cause of adhesion failures - filament that
has absorbed water vapor is bad at forming inter-layer bonds. Buy a cheap
hygrometer to put near your printer; if 40+% humidity is at all common
where you live, you need to get a filament dryer and cycle your
filament through it to avoid messy
disasters. https://www.reddit.com/r/3Dprinting/comments/15plahp/what_filament_dryer_would_you_recommend/[This
Reddit post] goes into more detail.  Apply this handy table; it
assumes ambient humidity 50%, 25°C (77°F), 1kg filament spool, scale
as needed:

[frame="topbot",options="header"]
|===================================================================
| Filament   |  Temperature  |   Time (Hours)
| PLA        |  55°C (131°F) |    > 6
| ABS        |  65°C (149°F) |    > 6
| PETG       |  65°C (149°F) |    > 6
| Nylon      |  75°C (167°F) |    > 24
| Desiccants |  65°C (149°F) |    > 6
| PVA        |  45°C (113°F) |    > 24
| TPU/TPE    |  55°C (131°F) |    > 8
| ASA        |  65°C (149°F) |    > 8
| PP         |  55°C (131°F) |    > 6
| HIPS       |  65°C (149°F) |    > 8
| PC         |  75°C (167°F) |    > 12
| PEEK       | 120°C (248°F) |    > 24
|===================================================================

Disposing of failed prints and scrap in an ecologically safe way is a
real problem. No common filaments will break down in landfills or
compost piles; PLA can be recycled, but only industrially (55–60 °C,
high humidity, microbial action). Some municipal recycling programs
handle PLA under "bioplastics", but many don't. Check in with local
plastics recyclers or university/makerspace programs.

== Diagnosing Print Failures

If you get horrible spaghetti (especially if you get it after a run of
good prints) the first thing to suspect is moist filament. There's no
fix for this short of a filament dryer.

If your printer stops extruding in mid-print, you probably have either
a spool tangle or a nozzle clog.

Check for a tangle by joggling the filament spool to see if it
spins freely and filament can unroll off of it with a straight
path in the printer.

Verifying that you have a nozzle clog is difficult because you can't
see inside the nozzle. But the basic procedure for clearing a clog is
fast and easy; apply it any time you suspect a clog.

== Basic De-Clogging:

Printer manufacturers often ship basic de-clogging tools - a push rod
and a needle - with your printer. Alas, they are usually too
lightweight and finicky for the application.

Get your hands on a more robust tool like the https://noclogger.com/[NoClogger].
Or just a piece of plain rod stock with a 1.5mm diameter - the pointy
end is nice but not essential.

1. Unload filament in the normal way.

2. Unship the PTFE tube at the toolhead end.

2. Heat the nozzle back up to melt temperature or above -
   higher is better for this purpose.

3. Push your your poker down the filament channel. Don't be afraid to
   use force, the throat interior is hard metal and difficult to
   damage.

4. You're looking for filament to drool out of the nozzle; that's
   your melted clog.

// end
