= Tuning and Customizations
// batchspell: add cfg 

If you found this before the link:setup.adoc[Sovol SV08 Build and Setup Guide],
you should probably read that first.

This is a guide to tuning and improving your Sovol SV08
after it has passed initial acceptance tests.

Each mod here is intended to be small, self-contained, and
self-explanatory. If you don't understand what it's doing, file an
issue against this repository.

== Temperature-controlled fan

Early videos on the SV08 were full of complaints about the mainboard
fan being extremely loud. This is no longer a problem on 08s
manufactured in 2025, but it's still a good idea to quiet your printer
and extend the fan's lifetime by applying John Hansknecht's CPU fan
control mod. A good place for this is after the fan3 control code,
about printer.cfg:375 in a stock installation:

// batchspell: off
----
[temperature_fan CPUfan]
pin: PA1
kick_start_time: 0.5
max_power: 1.0
min_temp: 0
max_temp: 90
hardware_pwm: true
target_temp: 60
sensor_type: temperature_host
max_speed: 1.0
min_speed: 0
control: pid
pid_Kp: 2     
pid_Ki: .5     
pid_Kd: 0.25     
pid_deriv_time: 5.0
----
// batchspell: on

This mod was first described at
https://www.youtube.com/watch?v=t3RJ5DbOdcs

== Improved bed leveling

This is gerGo's probe fix.  It makes bed leveling a bit slower but
more accurate, giving you better first layers. There are several mods
like this floating around the user community; they're all variations
on the theme of "go a bit slower, take more samples, get more accuracy".

// batchspell: off
----
[probe]
pin: extra_mcu:PB6
x_offset: -17                  
y_offset: 10             
#z_offset : 0
speed: 10  #  was 15.0
speed: 10.0  # was 5.0
samples: 3  # was 2
sample_retract_dist: 5.0 # was 2.0
lift_speed: 25 # was 50
samples_result: median # was average
samples_tolerance: 0.0125 # was 0.016
samples_tolerance_retries: 10 # was 2
----
// batchspell: on

This mod was first described at
https://www.youtube.com/watch?v=xl4tBgMcuzA

== Heat soaking

You can use this macro to ensure the bed is up to a uniform
temperature correct for printing before starting a print.
You can call it from the Mainsail console like this:
"HEAT_SOAK TEMPERATURE=80". If you don't specify a temperature
it will target 65C, which is good for generic PLA or PETG.

To install, put it anywhere in Macro.cfg or printer.cfg.

// batchspell: off
----
[gcode_macro HEAT_SOAK]
gcode:
  {% set soaktemp = params.TEMPERATURE|default(65)|int %}
  M117 Heat soak...
  M140 T0 S{soaktemp}
  {% if printer.toolhead.homed_axes != "xyz" %}
    G28
  {% endif %}
  G90 
  G1 Z5 F6000
  M84
----
// batchspell: on
